### ISSUE TITLE
Disable transitions/animations by default for prefers reduced motion

### ISSUE THREAD

**Issue by ediblecode** [nhsevidence/nice-design-system#72]
Something like:

```scss
@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.001s !important;
    transition-duration: 0.001s !important;
  }
}
```

**Comment by ediblecode** [comment]
Possibly this is better, to include animations as well as transitions:

```scss
// Disable animations/transitions according to users's preference
// See https://web.dev/prefers-reduced-motion/
@media (prefers-reduced-motion: reduce) {
  *,
  ::before,
  ::after {
    animation-delay: -1ms !important;
    animation-duration: 1ms !important;
    animation-iteration-count: 1 !important;
    background-attachment: initial !important;
    scroll-behavior: auto !important;
    transition-delay: 0s !important;
    transition-duration: 0s !important;
  }
}
```
